SELECT
  DATA.USERNAME,
  SUM(DATA.WIN) AS WIN,
  SUM(DATA.LOSE) AS LOSE
FROM (
  -- SELECT ALL WINNERS
  SELECT
    USERS.NAME AS USERNAME,
    SUM(1)     AS WIN,
    0          AS LOSE
  FROM GAMES
    LEFT JOIN USERS
      ON GAMES.WINNERID = USERS.ID
  WHERE
    NOT GAMES.WINNERID IS NULL    /* game has a winner */
    AND GAMES.STATUS = 'FINISHED' /* game finished */
  GROUP BY
    USERNAME

  UNION ALL

  -- SELECT ALL BLACK LOSERS
  SELECT
    USERS.NAME,
    0,
    SUM(1)
  FROM GAMES
    LEFT JOIN USERS
      ON GAMES.USERBLACKID = USERS.ID
  WHERE
    NOT GAMES.WINNERID IS NULL      /* game has a winner */
    AND GAMES.STATUS = 'FINISHED'   /* game finished */
    AND GAMES.USERBLACKID != GAMES.WINNERID   /* user wasn't a winner */
  GROUP BY
    USERS.NAME

  UNION ALL

  -- SELECT ALL WHITE LOSERS
  SELECT
    USERS.NAME,
    0,
    SUM(1)
  FROM GAMES
    LEFT JOIN USERS
      ON GAMES.USERWHITEID = USERS.ID
  WHERE
    NOT GAMES.WINNERID IS NULL     /* game has a winner */
    AND GAMES.STATUS = 'FINISHED'  /* game finished */
    AND GAMES.USERWHITEID != GAMES.WINNERID /* user wasn't a winner */
  GROUP BY
    USERS.NAME
) AS DATA
GROUP BY
  DATA.USERNAME
